server:
  port: 9091
  servlet:
    context-path: /
spring:
  application:
    name: crypto-binance
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB
springdoc:
  swagger-ui:
    path: /api
crypto:
  searching:
    interval-seconds: 20
  default-mode: OFFLINE