server:
  port: 9091
  servlet:
    context-path: /
#  ssl:
#    key-store: classpath:keystore/crypto.p12
#    key-store-password: crypto
#    key-alias: crypto
#    enabled: true
spring:
  application:
    name: crypto-binance
#  security:
#    user:
#      name: crypto
#      password: crypto
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB